services:
  # Backend (Django)
  backend:
    build:
      context: ./duty-chart-backend
      dockerfile: Dockerfile
    container_name: duty-chart-backend
    volumes:
      - ./duty-chart-backend:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db

  # Database (Postgres)
  db:
    image: postgres:15
    container_name: duty-chart-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - "5432:5432"

  # Frontend (React + Nginx)
  frontend:
    build:
      context: ./duty-chart-frontend
      dockerfile: Dockerfile
    container_name: duty-chart-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
  static_volume:
  media_volume:
