# Generated by Django 5.0.2 on 2025-07-24 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('duties', '0001_initial'),
        ('org', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='duty',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dutychart',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_charts', to='org.office'),
        ),
        migrations.AddField(
            model_name='duty',
            name='duty_chart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duties', to='duties.dutychart'),
        ),
        migrations.AlterUniqueTogether(
            name='duty',
            unique_together={('duty_chart', 'date', 'shift')},
        ),
    ]
