# Generated by Django 5.2.5 on 2025-08-21 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0003_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('shift', models.CharField(choices=[('morning', 'Morning'), ('day', 'Day'), ('night', 'Night')], db_index=True, max_length=10)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user_id', 'date'],
                'indexes': [models.Index(fields=['user', 'date'], name='duties_sche_user_id_74adc8_idx'), models.Index(fields=['shift', 'date'], name='duties_sche_shift_541d39_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='unique_schedule_user_date')],
            },
        ),
    ]
