# Generated by Django 5.2.5 on 2025-08-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0004_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='RosterShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RosterAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('shift', models.CharField(db_index=True, max_length=50)),
                ('employee', models.CharField(db_index=True, max_length=255)),
                ('network', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date', 'shift', 'employee'],
                'indexes': [models.Index(fields=['date', 'shift'], name='duties_rost_date_87c459_idx'), models.Index(fields=['employee'], name='duties_rost_employe_c1bea2_idx')],
                'unique_together': {('date', 'shift', 'employee')},
            },
        ),
    ]
