# Generated by Django 5.2.5 on 2025-08-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0005_rostershift_rosterassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='dutychart',
            name='employee_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dutychart',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
