# Generated by Django 5.2.5 on 2025-08-25 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0006_dutychart_employee_name_dutychart_phone_number'),
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rosterassignment',
            name='network',
        ),
        migrations.AddField(
            model_name='rosterassignment',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roster_assignments', to='org.office'),
        ),
    ]
