# Generated by Django 5.2.5 on 2025-08-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0009_alter_rosterassignment_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='rosterassignment',
            constraint=models.UniqueConstraint(fields=('employee_name', 'office', 'start_date', 'end_date', 'start_time', 'end_time', 'shift'), name='uniq_rosterassignment_emp_office_span_times_shift'),
        ),
    ]
