# Generated by Django 5.2.5 on 2025-08-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0010_rosterassignment_uniq_rosterassignment_emp_office_span_times_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rosterassignment',
            name='shift',
            field=models.CharField(max_length=20),
        ),
    ]
