# Generated by Django 5.2.5 on 2025-08-29 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0011_alter_rosterassignment_shift'),
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='schedule',
            name='unique_schedule_user_date',
        ),
        migrations.RemoveIndex(
            model_name='schedule',
            name='duties_sche_user_id_74adc8_idx',
        ),
        migrations.RemoveIndex(
            model_name='schedule',
            name='duties_sche_shift_541d39_idx',
        ),
        migrations.AddField(
            model_name='schedule',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='org.office'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='shift',
            field=models.CharField(max_length=50),
        ),
    ]
