# Generated by Django 5.2.5 on 2025-09-01 08:03

from django.db import migrations, models


def copy_date_to_start_date(apps, schema_editor):
    Schedule = apps.get_model('duties', 'Schedule')
    # Copy old 'date' values into new 'start_date'
    if hasattr(Schedule, 'date'):
        for obj in Schedule.objects.all():
            if obj.date:
                obj.start_date = obj.date
                obj.save(update_fields=['start_date'])


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0012_alter_schedule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='start_date',
            field=models.DateField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='end_date',
            field=models.DateField(null=True, blank=True),
        ),
        migrations.RunPython(copy_date_to_start_date, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='schedule',
            name='date',
        ),
    ]
