# Generated by Django 5.2.5 on 2025-09-01 08:37

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0013_auto_20250901_0803'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['start_date', 'employee_name']},
        ),
        migrations.AddField(
            model_name='schedule',
            name='employee_name',
            field=models.CharField(default='__Missing__', max_length=255),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_time',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='office',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='shift',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('employee_name', 'office', 'start_date', 'end_date', 'start_time', 'end_time', 'shift'), name='uniq_schedule_emp_office_span_times_shift'),
        ),
    ]
