# Generated by Django 5.2.5 on 2025-08-25 09:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0007_remove_rosterassignment_network_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='size',
            field=models.PositiveIntegerField(help_text='File size in bytes', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52428800)]),
        ),
        migrations.AlterField(
            model_name='dutychart',
            name='phone_number',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.RegexValidator('^\\+977\\d{10}$', 'Enter a valid Nepal phone number starting with +977 followed by exactly 10 digits.')]),
        ),
    ]
