# Generated by Django 5.2.5 on 2025-08-27 06:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0008_alter_document_size_alter_dutychart_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rosterassignment',
            options={'ordering': ['start_date', 'employee_name']},
        ),
        migrations.RemoveIndex(
            model_name='rosterassignment',
            name='duties_rost_date_87c459_idx',
        ),
        migrations.RemoveIndex(
            model_name='rosterassignment',
            name='duties_rost_employe_c1bea2_idx',
        ),
        migrations.AlterUniqueTogether(
            name='rosterassignment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='rosterassignment',
            name='employee_name',
            field=models.CharField(default='__Missing__', max_length=255),
        ),
        migrations.AddField(
            model_name='rosterassignment',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rosterassignment',
            name='end_time',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AddField(
            model_name='rosterassignment',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rosterassignment',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rosterassignment',
            name='start_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AddField(
            model_name='rosterassignment',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='rosterassignment',
            name='office',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rosterassignment',
            name='shift',
            field=models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening'), ('night', 'Night')], max_length=20),
        ),
        migrations.RemoveField(
            model_name='rosterassignment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='rosterassignment',
            name='employee',
        ),
    ]
