# Generated by Django 5.2.5 on 2025-09-03 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0014_alter_schedule_options_schedule_employee_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='user',
        ),
    ]
